server:
  port: 9301  #服务端口号

spring:
  profiles:
    active: dev
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: ${spring.configurl}
          search-paths: '{application}/{profile}'
            username: huangdingke
            password: Qq11234566
            clone-on-start: true
  rabbitmq:
    host: 192.168.2.22
    port: 5672
    username: guest
    password: guest
    requested-heartbeat: 60s
    listener:
      direct:
        acknowledge-mode: none

eureka:
  client:
    serviceUrl:
      defaultZone: ${spring.eurekaurl}
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true


---
spring:
  profiles: dev
  configurl: https://github.com/huangdingke/msc-config-client.git
---
spring:
  profiles: test
  configurl: https://github.com/huangdingke/msc-config-client.git
---